### ISSUE TITLE
Base request URL doesn't exist anymore

### ISSUE THREAD

**Issue by SjoerdMO4** [fboerman/TenneT-py#1]
It looks like TenneT has moved the URL to do requests to a different location as it doesn't work anymore.

**Comment by fboerman** [comment]
hi, tennet.org has been decommisioned. you should use the new tennet.eu API. You can request an API key here: https://www.tennet.eu/registration-api-token
for mass download of data you can go here: https://www.tennet.eu/markets/transparency-data-netherlands/download-transparency
I have created a new package for the new api here: https://github.com/fboerman/TenneTeu-py
